name: Deploy to Azure Web App

on:
  push:
    branches:
      - main_dev
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Select Publish Profile based on Branch
      id: publish-profile
      run: |
        if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
          echo "Using Production Publish Profile"
          echo "PUBLISH_PROFILE=${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}" >> $GITHUB_ENV
        elif [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
          echo "Using Development Publish Profile"
          echo "PUBLISH_PROFILE=${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}" >> $GITHUB_ENV
        fi

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'csels-pd-towerscrt-dev-web-01'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
        package: .
