name: Deploy Flask App to Azure FTP

on:
  push:
    branches:
    - main
    - main_dev   # Development branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can choose 'windows-latest' or 'macos-latest' if needed

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Replace with the version of Python you are using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt

     # - name: Set up Azure CLI
     #   uses: azure/azure-cli-action@v1
        
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
          auth-type: SERVICE_PRINCIPAL
          
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      # Step 4: Conditional Deployment Based on Branch (Dev or Prod)
      - name: Deploy to Azure Web App (Dev or Prod)
        uses: azure/webapps-deploy@v3
        with:
          # Use conditional expressions to set app name based on the branch
          app-name: 'csels-pd-towerscrt-dev-web-01'
          slot-name: 'towerscout-master'
          
          # Use conditional expressions to set the publish profile based on the branch
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}

          package: .  # Path to the application, deploy the entire repo
