# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions. Checking if redeployment from git will cause login screen issues

name: Build and deploy Python app to Azure Web App - csels-pd-towerscrt-dev-web-01 self hosted runner

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '.github/workflows/azure-deployment.yml'
  workflow_dispatch:

jobs:

  build:
    runs-on:
      - L383058
      - TowerScout
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and activate virtual environment
        shell: powershell
        run: |
          python -m venv venv
          $env:Path = "$PWD\venv\Scripts;$env:Path"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python --version


      
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Create zip release file
        shell: powershell
        run: |
          $files = Get-ChildItem -Path $PWD -Exclude 'release.zip'  # Avoid zipping the output itself
          Compress-Archive -Path $files -DestinationPath release.zip -Force
        working-directory: ${{ github.workspace }}


  


     # - name: Upload artifact for deployment jobs
     #   uses: actions/upload-artifact@v4
     #   with:
     #     name: python-app
     #     path: |
     #       release.zip
     #       !venv/
  deploy:
    runs-on: self-hosted
      #group: edav-devops
    needs: build
    environment:
      name: 'towerscoutdev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      #- name: Download artifact from build job
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: python-app

      - name: Unzip release.zip
        shell: cmd
        run: powershell -Command "Expand-Archive -Path 'release.zip' -DestinationPath '.' -Force"



      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'csels-pd-towerscrt-dev-web-01'
          slot-name: 'towerscoutdev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_30C48FEAEE0E493DB701B1A20F915C81 }}

